version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "tests/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "dev-requirements.txt",
  "requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 119

[[transformers]]
name = "black"
enabled = false

[[transformers]]
name = "prettier"
enabled = true
